import { Locale } from "./types";

export const uiCopy: Record<Locale, Record<string, string>> = {
  en: {
    catalog: "Catalog",
    featured: "Featured Picks",
    addToCart: "Add to cart",
    searchPlaceholder: "Search by product, collection, or shade",
    search: "Search",
    sort: "Sort",
    allProducts: "All products",
    category: "Category",
    relatedProducts: "Recommended with this item",
    inStock: "In stock",
    lowStock: "Low stock",
    outOfStock: "Out of stock",
    cart: "Cart",
    checkout: "Checkout",
    subtotal: "Subtotal",
    shipping: "Shipping",
    vatIncluded: "VAT included",
    total: "Total",
    admin: "Admin",
    orders: "Orders",
    products: "Products",
    content: "Content",
    emptyCart: "Your cart is empty.",
    continueShopping: "Continue shopping",
    placeOrder: "Create payment",
    orderConfirmed: "Order received",
    localeSwitch: "Language"
  },
  lv: {
    catalog: "Katalogs",
    featured: "Izceltie produkti",
    addToCart: "Pievienot grozam",
    searchPlaceholder: "Meklet pec produkta, kolekcijas vai tona",
    search: "Meklet",
    sort: "Kartot",
    allProducts: "Visi produkti",
    category: "Kategorija",
    relatedProducts: "Ieteicams kopa ar so produktu",
    inStock: "Ir noliktava",
    lowStock: "Maz atlikuma",
    outOfStock: "Nav noliktava",
    cart: "Grozs",
    checkout: "Noformet pasutijumu",
    subtotal: "Starpsumma",
    shipping: "Piegade",
    vatIncluded: "PVN ieklauts",
    total: "Kopa",
    admin: "Administracija",
    orders: "Pasutijumi",
    products: "Produkti",
    content: "Saturs",
    emptyCart: "Grozs ir tukss.",
    continueShopping: "Turpinat iepirkties",
    placeOrder: "Izveidot maksajumu",
    orderConfirmed: "Pasutijums sanemts",
    localeSwitch: "Valoda"
  }
};
